<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="10" passed="3" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-06T18:32:14 EST" name="All Test Suite" finished-at="2023-03-06T18:34:53 EST" duration-ms="159385">
    <groups>
      <group name="excel">
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
      </group> <!-- excel -->
      <group name="regression">
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
        <method signature="AddEmployeeTest.addEmployeeTest()[pri:0, instance:com.exelenter.testcases.AddEmployeeTest@20d525]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeTest"/>
        <method signature="LoginTest.validAdminLogin()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" name="validAdminLogin" class="com.exelenter.testcases.LoginTest"/>
        <method signature="LoginTest.validUserEmptyPassword()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" name="validUserEmptyPassword" class="com.exelenter.testcases.LoginTest"/>
        <method signature="LoginTest.validUserInvalidPassword()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" name="validUserInvalidPassword" class="com.exelenter.testcases.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-03-06T18:32:14 EST" name="Smoke Test" finished-at="2023-03-06T18:34:53 EST" duration-ms="159385">
      <class name="com.exelenter.testcases.AddEmployeeTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeTest@20d525]" started-at="2023-03-06T18:34:33 EST" name="setUp" finished-at="2023-03-06T18:34:34 EST" duration-ms="1263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest()[pri:0, instance:com.exelenter.testcases.AddEmployeeTest@20d525]" started-at="2023-03-06T18:34:34 EST" name="addEmployeeTest" finished-at="2023-03-06T18:34:38 EST" duration-ms="3062" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeTest@20d525]" started-at="2023-03-06T18:34:38 EST" name="tearDown" finished-at="2023-03-06T18:34:40 EST" duration-ms="2067" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.testcases.AddEmployeeTest -->
      <class name="com.exelenter.testcases.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:40 EST" name="setUp" finished-at="2023-03-06T18:34:41 EST" duration-ms="1651" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validAdminLogin()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:41 EST" name="validAdminLogin" finished-at="2023-03-06T18:34:42 EST" duration-ms="1207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validAdminLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:42 EST" name="tearDown" finished-at="2023-03-06T18:34:45 EST" duration-ms="2076" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:45 EST" name="setUp" finished-at="2023-03-06T18:34:46 EST" duration-ms="1939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validUserEmptyPassword()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:46 EST" name="validUserEmptyPassword" finished-at="2023-03-06T18:34:47 EST" duration-ms="103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserEmptyPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:47 EST" name="tearDown" finished-at="2023-03-06T18:34:49 EST" duration-ms="2084" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:49 EST" name="setUp" finished-at="2023-03-06T18:34:50 EST" duration-ms="1489" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validUserInvalidPassword()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:50 EST" name="validUserInvalidPassword" finished-at="2023-03-06T18:34:51 EST" duration-ms="847" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.exelenter.testcases.LoginTest.validUserInvalidPassword(LoginTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserInvalidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.LoginTest@6200f9cb]" started-at="2023-03-06T18:34:51 EST" name="tearDown" finished-at="2023-03-06T18:34:53 EST" duration-ms="2094" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.testcases.LoginTest -->
      <class name="com.exelenter.testcases.AddEmployeeFromExcel">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:32:14 EST" name="setUp" finished-at="2023-03-06T18:32:26 EST" duration-ms="12393" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:32:26 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-06T18:32:49 EST" duration-ms="22604" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sophia]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Patel]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[sophiapatel1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[eL!2mE&0uM?3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:32:49 EST" name="tearDown" finished-at="2023-03-06T18:32:51 EST" duration-ms="2075" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:32:51 EST" name="setUp" finished-at="2023-03-06T18:32:52 EST" duration-ms="1235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:32:52 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-06T18:33:14 EST" duration-ms="21639" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Jackson]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chen]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[jacksonchen1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[uW~3tC(5eZ^3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:33:14 EST" name="tearDown" finished-at="2023-03-06T18:33:16 EST" duration-ms="2076" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:33:16 EST" name="setUp" finished-at="2023-03-06T18:33:18 EST" duration-ms="1556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:33:18 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-06T18:33:41 EST" duration-ms="23330" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Isabella]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rodriguez]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[irodriguez]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[cF,5eS?8oM:3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:33:41 EST" name="tearDown" finished-at="2023-03-06T18:33:43 EST" duration-ms="2077" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:33:43 EST" name="setUp" finished-at="2023-03-06T18:33:44 EST" duration-ms="1245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:33:44 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-06T18:34:06 EST" duration-ms="21261" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Caleb]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Thomson]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[calebthomson1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[lT?4kA]2zB~9]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:34:06 EST" name="tearDown" finished-at="2023-03-06T18:34:08 EST" duration-ms="2066" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:34:08 EST" name="setUp" finished-at="2023-03-06T18:34:09 EST" duration-ms="1250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:34:09 EST" name="addEmployeeTest" data-provider="addEmployees" finished-at="2023-03-06T18:34:31 EST" duration-ms="22119" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Zoe]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Kim]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[zoekim1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[tF_1jE_2fK#3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@55fe41ea]" started-at="2023-03-06T18:34:31 EST" name="tearDown" finished-at="2023-03-06T18:34:33 EST" duration-ms="2070" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.testcases.AddEmployeeFromExcel -->
    </test> <!-- Smoke Test -->
  </suite> <!-- All Test Suite -->
</testng-results>
